services:
  frontend:
    build: ../frontend
    volumes:
      - ../frontend/src:/app/src
    environment:
      - VITE_API_HOST=http://localhost:7091
      - VITE_API_STREAMING=$VITE_API_STREAMING
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    user: root
    build: ../application
    environment:
      - API_KEY=$API_KEY
      - EMBEDDINGS_KEY=$API_KEY
      - LLM_NAME=$LLM_NAME
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - CACHE_REDIS_URL=redis://redis:6379/2
      - OPENAI_BASE_URL=$OPENAI_BASE_URL
      - MODEL_NAME=$MODEL_NAME
    ports:
      - "7091:7091"
    volumes:
      - ../application/indexes:/app/application/indexes
      - ../application/inputs:/app/inputs
      - ../application/vectors:/app/application/vectors
    depends_on:
      - redis
      - mongo

  worker:
    user: root
    build: ../application
    command: celery -A application.app.celery worker -l INFO -B
    environment:
      - API_KEY=$API_KEY
      - EMBEDDINGS_KEY=$API_KEY
      - LLM_NAME=$LLM_NAME
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - API_URL=http://backend:7091
      - CACHE_REDIS_URL=redis://redis:6379/2
    volumes:
      - ../application/indexes:/app/application/indexes
      - ../application/inputs:/app/inputs
      - ../application/vectors:/app/application/vectors
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
