name: docsgpt-oss
services:

  frontend:
    image: arc53/docsgpt-fe:develop
    environment:
      - VITE_API_HOST=http://localhost:7091
      - VITE_API_STREAMING=${VITE_API_STREAMING:-true}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID:-}
    ports:
      - "5173:5173"
    depends_on:
      - backend


  backend:
    user: root
    image: arc53/docsgpt:develop
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - CACHE_REDIS_URL=redis://redis:6379/2
    ports:
      - "7091:7091"
    volumes:
      - ../application/indexes:/app/indexes
      - ../application/inputs:/app/inputs
      - ../application/vectors:/app/vectors
    depends_on:
      - redis
      - mongo


  worker:
    user: root
    image: arc53/docsgpt:develop
    command: celery -A application.app.celery worker -l INFO -B
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - MONGO_URI=mongodb://mongo:27017/docsgpt
      - API_URL=http://backend:7091
      - CACHE_REDIS_URL=redis://redis:6379/2
    volumes:
      - ../application/indexes:/app/indexes
      - ../application/inputs:/app/inputs
      - ../application/vectors:/app/vectors
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  mongo:
    image: mongo:6
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: