apiVersion: v1
kind: Secret
metadata:
  name: docsgpt-secrets
type: Opaque
data:
  LLM_NAME: ZG9jc2dwdA==
  INTERNAL_KEY: aW50ZXJuYWw=
  CELERY_BROKER_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA==
  CELERY_RESULT_BACKEND: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA==
  QDRANT_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA==
  QDRANT_PORT: NjM3OQ==
  MONGO_URI: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9kb2NzZ3B0P3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  mongo-user: bW9uZ28tdXNlcg==
  mongo-password: bW9uZ28tcGFzc3dvcmQ=